language: java

# Remove lock files before caching
before_cache:
  - rm -f  $HOME/.gradle/caches/*/*.lock

# Cache only relevant directories
cache:
  directories:
    - $HOME/.gradle/caches/modules-2
    - $HOME/.gradle/wrapper/dists

install:
  - ./gradlew --version # Display Gradle, Groovy, JVM and other versions

jdk:
  - openjdk11
  - openjdk-ea

os:
  - linux
  - osx

matrix:
  exclude:
    - os: osx
      jdk: openjdk-ea
  allow_failures:
    - jdk: openjdk-ea

script:
  - ./gradlew --warning-mode=all build check

after_success:
  - bash <(curl -s https://codecov.io/bash)
