/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
  public boolean someLibraryMethod() {
    return true;
  }

  public static double circumference(double diameter) {
    return diameter * 3;
  }
}
